import { StyleSheet } from "react-native";
import base from "./theme.json";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    marginTop: 20,
    gap: 10,
    justifyContent: "center",
    backgroundColor: base.colors.background,
  },
  calendar: {
    flex: 1,
    overflow: "hidden",
    justifyContent: "center",
    backgroundColor: base.colors.background,
    borderRadius: 20,
    borderColor: base.colors.border,
    borderWidth: 1,
  },
  title: {
    textAlign: "center",
    fontSize: 20,
    color: base.colors.text,
  },
  input: {
    backgroundColor: base.colors.inputBackground,
    minHeight: 40,
    padding: 15,
    fontSize: 20,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: base.colors.border,
  },
  button: {
    backgroundColor: base.colors.primary,
    borderColor: base.colors.secondary,
    borderWidth: 1,
    padding: 10,
    marginVertical: 5,
    borderRadius: 15,
    alignItems: "center",
  },
  scrollContainer: { paddingBottom: 40 },
  inputGroup: { marginBottom: 20 },
  separator: { fontSize: 20, fontWeight: "bold", color: "#ccc" },
  card: {
    backgroundColor: base.colors.surface,
    borderColor: base.colors.border,
    justifyContent: "center",
    borderRadius: 16,
    gap: 10,
    padding: 16,
    marginBottom: 20,
    borderWidth: 1,
    shadowColor: base.colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  label: {
    fontSize: 20,
    color: base.colors.textSecondary,
    fontWeight: "600",
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 12,
  },
});
